/**
 * PR-comment output.
 *
 * Written to be read in a GitHub thread, which shapes several choices: the
 * verdict is in the heading so it survives the collapsed preview, the issue
 * table is capped so the comment does not dominate the page, and the
 * remediation code sits inside `<details>` so it is available without being in
 * the way.
 *
 * The comment carries a stable HTML marker so a workflow can find and update
 * its previous comment instead of posting a new one on every push.
 */

import {
  generateRemediation,
  type AgentScorecard,
  type AuditIssue,
  type IssueSeverity,
} from '@agentgrade/core';

import type { AuditRunResult } from '../audit.js';

/** Identifies an AgentGrade comment so a workflow can update it in place. */
export const COMMENT_MARKER = '<!-- agentgrade-report -->';

const SEVERITY_ICON: Record<IssueSeverity, string> = {
  critical: '🔴',
  warning: '🟡',
  info: '🔵',
};

export interface MarkdownOptions {
  /** How many issues to table. Default 10. */
  maxIssues?: number;
  /** Include generated remediation code for the top issue. Default `true`. */
  includeRemediation?: boolean;
  /** Repo-relative title, when the workflow knows the environment. */
  title?: string;
}

/** Formats a run as a GitHub-flavoured markdown comment body. */
export function formatMarkdown(result: AuditRunResult, options: MarkdownOptions = {}): string {
  const { scorecard } = result;
  const maxIssues = options.maxIssues ?? 10;
  const verdict = result.passed ? '✅ **PASS**' : '❌ **FAIL**';
  const lines: string[] = [];

  lines.push(COMMENT_MARKER);
  lines.push(
    `## ${verdict} — AgentGrade ${scorecard.grade} (${scorecard.overallScore}/100)`,
    '',
    `${options.title ? `**${cell(options.title)}** · ` : ''}\`${cell(result.url)}\` · threshold **${result.threshold}** · scanned in ${(result.durationMs / 1000).toFixed(1)}s`,
    '',
  );

  if (!result.passed) {
    const shortfall = result.threshold - scorecard.overallScore;
    lines.push(
      `> This build is blocked: the score is **${shortfall}** point(s) below the required threshold.`,
      '',
    );
  }

  lines.push(...renderTaxSection(scorecard));
  lines.push(...renderPillarSection(scorecard));
  lines.push(...renderIssueSection(scorecard.issues, maxIssues));

  if (options.includeRemediation !== false) {
    lines.push(...renderRemediationSection(result));
  }

  lines.push(
    '',
    '<sub>Generated by [AgentGrade](https://github.com/gdavos007/AgentReady-Studio) — WebMCP and AI-agent readiness auditing.</sub>',
  );

  return clampComment(`${lines.join('\n')}\n`);
}

/** The savings table — the part a non-engineer reads. */
function renderTaxSection(scorecard: AgentScorecard): string[] {
  const { domTraversal, webMcpDirect, frictionTax } = scorecard.benchmark;

  return [
    '### Agent Friction Tax',
    '',
    prose(frictionTax.headline),
    '',
    `| | DOM traversal | WebMCP direct | Saved |`,
    `| --- | ---: | ---: | ---: |`,
    `| Steps | ${domTraversal.steps} | ${webMcpDirect.steps} | ${domTraversal.steps - webMcpDirect.steps} |`,
    `| Tokens | ${formatCompact(domTraversal.totalTokens)} | ${formatCompact(webMcpDirect.totalTokens)} | ${formatCompact(frictionTax.tokensWasted)} |`,
    `| Cost | ${formatUsd(domTraversal.costUsd)} | ${formatUsd(webMcpDirect.costUsd)} | ${formatUsd(frictionTax.costWastedUsd)} |`,
    `| Latency | ${(domTraversal.latencyMs / 1000).toFixed(1)}s | ${(webMcpDirect.latencyMs / 1000).toFixed(1)}s | ${frictionTax.secondsWasted.toFixed(1)}s |`,
    `| Failure risk | ${(domTraversal.failureProbability * 100).toFixed(1)}% | ${(webMcpDirect.failureProbability * 100).toFixed(1)}% | ${(frictionTax.failureProbabilityDelta * 100).toFixed(1)}pp |`,
    '',
    `<sub>Per user transaction, modelled for a **${escapeHtml(scorecard.benchmark.goal)}** flow at ${escapeHtml(scorecard.benchmark.pricing.model)} rates. Estimates — see the report for stated assumptions.</sub>`,
    '',
  ];
}

function renderPillarSection(scorecard: AgentScorecard): string[] {
  const rows = scorecard.pillars.map((pillar) => {
    const ratio = pillar.maxPoints > 0 ? pillar.weightedPoints / pillar.maxPoints : 0;
    return `| ${cell(pillar.label)} | ${meter(ratio)} | ${pillar.weightedPoints.toFixed(1)} / ${pillar.maxPoints} |`;
  });

  return ['### Pillars', '', '| Pillar | | Score |', '| --- | --- | ---: |', ...rows, ''];
}

function renderIssueSection(issues: AuditIssue[], maxIssues: number): string[] {
  if (issues.length === 0) return ['### Issues', '', 'No issues found. 🎉', ''];

  const shown = issues.slice(0, maxIssues);
  const rows = shown.map(
    (issue) =>
      `| ${SEVERITY_ICON[issue.severity]} | **${cell(issue.title)}** | ${
        issue.deductionPoints > 0 ? `−${issue.deductionPoints.toFixed(2)}` : '—'
      } | ${cell(issue.remediation)} |`,
  );

  const lines = [
    `### Top deductions`,
    '',
    '| | Issue | Points | Fix |',
    '| :-: | --- | ---: | --- |',
    ...rows,
    '',
  ];

  if (issues.length > shown.length) {
    lines.push(`<sub>${issues.length - shown.length} further issue(s) omitted.</sub>`, '');
  }

  return lines;
}

/**
 * Generated code for the costliest issue.
 *
 * One issue, not all of them: a comment that dumps every snippet is a comment
 * nobody reads. The single highest-value fix is the one worth putting in front
 * of a reviewer.
 */
function renderRemediationSection(result: AuditRunResult): string[] {
  const [top] = result.scorecard.issues.filter((issue) => issue.deductionPoints > 0);
  if (!top) return [];

  let bundle;
  try {
    bundle = generateRemediation(top, result.report.data);
  } catch {
    // Code generation must never be the reason a CI comment fails to post.
    return [];
  }

  const tab = bundle.tabs.find((entry) => entry.id === 'browser-native') ?? bundle.tabs[0];
  if (!tab) return [];

  return [
    '<details>',
    `<summary><b>Suggested fix for the biggest deduction</b> — ${escapeHtml(top.title)} (−${top.deductionPoints.toFixed(2)})</summary>`,
    '',
    prose(bundle.summary),
    '',
    '```javascript',
    fencedCode(tab.code),
    '```',
    '',
    '</details>',
  ];
}

/** A five-cell bar that renders the same width in any markdown viewer. */
function meter(ratio: number): string {
  const filled = Math.round(Math.min(1, Math.max(0, ratio)) * 5);
  return '█'.repeat(filled) + '░'.repeat(5 - filled);
}

/* -------------------------------------------------------------------------- */
/* Sanitisation                                                                */
/* -------------------------------------------------------------------------- */

/*
 * Everything below exists because this comment is assembled from strings the
 * *audited site* chose. Issue titles quote its form field names, remediation
 * text quotes its tool names, and the generated snippet is built from its
 * declared schemas. The comment is then posted, by a workflow holding
 * `pull-requests: write`, into a repository that does not own the target.
 *
 * So a target is an untrusted author of part of this document, and the
 * failure modes are concrete: a backtick fence in a tool description escapes
 * the code block and the rest of the comment becomes attacker-authored
 * markdown; a `</details>` closes the collapsed section early; a megabyte of
 * generated text pushes the body past GitHub's 65536-character limit, the
 * API call 422s, and the comment that explains the red build never posts.
 */

/** GitHub rejects an issue comment body longer than this. */
const MAX_COMMENT_CHARS = 65_000;

/** Cap for one table cell, so a single issue cannot crowd out the rest. */
const MAX_CELL_CHARS = 300;

/** Cap for the generated snippet inside the `<details>` block. */
const MAX_CODE_CHARS = 4_000;

/** Characters that render as nothing but survive a copy-paste. */
// eslint-disable-next-line no-control-regex -- removing them is the point
const CONTROL_CHARS = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g;

/** Strips control characters and folds every line break into a space. */
function flatten(value: string): string {
  return String(value ?? '')
    .replace(CONTROL_CHARS, '')
    .replace(/\r\n?|\n/g, ' ');
}

/**
 * Makes one target-controlled string safe inside a table cell.
 *
 * A pipe would forge a column and a line break would end the row, so both are
 * neutralised. Angle brackets are entity-encoded: GitHub sanitises HTML in
 * comments, but "their allowlist will catch it" is exactly the assumption not
 * worth making, and no issue copy in this codebase contains one, so the
 * encoding costs nothing legible.
 *
 * Backticks are deliberately left alone. Real remediation text says things
 * like "annotate the form with `data-mcp-tool`", and a stray backtick cannot
 * escape a cell — GFM splits a row on its pipes before parsing any cell as
 * inline content, so a fence is not a construct that can start here.
 */
function cell(value: string): string {
  return clamp(
    flatten(value)
      .replace(/\|/g, '\\|')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;'),
    MAX_CELL_CHARS,
  );
}

/**
 * Makes one target-controlled string safe on a line of its own.
 *
 * Stricter than {@link cell}, because a standalone line is parsed as a block:
 * a leading `#` becomes a heading, a leading `>` a quote, and a run of three
 * backticks opens a fence that swallows everything after it — which is how a
 * target would take over the rest of the comment.
 */
function prose(value: string): string {
  return clamp(
    flatten(value)
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/`{3,}/g, (run) => "'".repeat(run.length))
      .replace(/^\s*([#>\-+*=]|\d+[.)])/, '\\$1'),
    MAX_CELL_CHARS,
  );
}

/**
 * Neutralises a fenced code block's contents.
 *
 * Every run of three or more backticks is broken up. Choosing a longer opening
 * fence instead would only move the problem: the target can always emit a
 * longer run than the one picked.
 */
function fencedCode(value: string): string {
  return clamp(String(value ?? '').trimEnd(), MAX_CODE_CHARS).replace(/`{3,}/g, (run) =>
    "'".repeat(run.length),
  );
}

/** Truncates on a hard character budget, saying so when it cuts. */
function clamp(value: string, limit: number): string {
  return value.length > limit ? `${value.slice(0, limit - 1)}\u2026` : value;
}

/**
 * Last line of defence on the assembled body.
 *
 * Every field is capped individually above, but the counts are not — a site
 * with two hundred unlabelled controls yields a legitimately long comment. A
 * truncated comment that posts is worth more than a complete one that 422s.
 */
function clampComment(body: string): string {
  if (body.length <= MAX_COMMENT_CHARS) return body;
  const notice =
    '\n\n<sub>Report truncated to fit GitHub\u2019s comment limit \u2014 see the uploaded artifact for the full scorecard.</sub>\n';
  return `${body.slice(0, MAX_COMMENT_CHARS - notice.length)}${notice}`;
}

function escapeHtml(value: string): string {
  return clamp(
    String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'),
    MAX_CELL_CHARS,
  );
}

function formatUsd(value: number): string {
  if (!Number.isFinite(value)) return '$0.00';
  return value >= 0.01 ? `$${value.toFixed(2)}` : `$${value.toFixed(4)}`;
}

function formatCompact(value: number): string {
  if (!Number.isFinite(value)) return '0';
  if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(1)}M`;
  if (value >= 1_000) return `${(value / 1_000).toFixed(1)}k`;
  return String(Math.round(value));
}
