/**
 * PR-comment output.
 *
 * Written to be read in a GitHub thread, which shapes several choices: the
 * verdict is in the heading so it survives the collapsed preview, the issue
 * table is capped so the comment does not dominate the page, and the
 * remediation code sits inside `<details>` so it is available without being in
 * the way.
 *
 * The comment carries a stable HTML marker so a workflow can find and update
 * its previous comment instead of posting a new one on every push.
 */

import {
  generateRemediation,
  type AgentScorecard,
  type AuditIssue,
  type IssueSeverity,
} from '@agentgrade/core';

import type { AuditRunResult } from '../audit.js';

/** Identifies an AgentGrade comment so a workflow can update it in place. */
export const COMMENT_MARKER = '<!-- agentgrade-report -->';

const SEVERITY_ICON: Record<IssueSeverity, string> = {
  critical: '🔴',
  warning: '🟡',
  info: '🔵',
};

export interface MarkdownOptions {
  /** How many issues to table. Default 10. */
  maxIssues?: number;
  /** Include generated remediation code for the top issue. Default `true`. */
  includeRemediation?: boolean;
  /** Repo-relative title, when the workflow knows the environment. */
  title?: string;
}

/** Formats a run as a GitHub-flavoured markdown comment body. */
export function formatMarkdown(result: AuditRunResult, options: MarkdownOptions = {}): string {
  const { scorecard } = result;
  const maxIssues = options.maxIssues ?? 10;
  const verdict = result.passed ? '✅ **PASS**' : '❌ **FAIL**';
  const lines: string[] = [];

  lines.push(COMMENT_MARKER);
  lines.push(
    `## ${verdict} — AgentGrade ${scorecard.grade} (${scorecard.overallScore}/100)`,
    '',
    `${options.title ? `**${options.title}** · ` : ''}\`${result.url}\` · threshold **${result.threshold}** · scanned in ${(result.durationMs / 1000).toFixed(1)}s`,
    '',
  );

  if (!result.passed) {
    const shortfall = result.threshold - scorecard.overallScore;
    lines.push(
      `> This build is blocked: the score is **${shortfall}** point(s) below the required threshold.`,
      '',
    );
  }

  lines.push(...renderTaxSection(scorecard));
  lines.push(...renderPillarSection(scorecard));
  lines.push(...renderIssueSection(scorecard.issues, maxIssues));

  if (options.includeRemediation !== false) {
    lines.push(...renderRemediationSection(result));
  }

  lines.push(
    '',
    '<sub>Generated by [AgentGrade](https://github.com/gdavos007/AgentReady-Studio) — WebMCP and AI-agent readiness auditing.</sub>',
  );

  return `${lines.join('\n')}\n`;
}

/** The savings table — the part a non-engineer reads. */
function renderTaxSection(scorecard: AgentScorecard): string[] {
  const { domTraversal, webMcpDirect, frictionTax } = scorecard.benchmark;

  return [
    '### Agent Friction Tax',
    '',
    frictionTax.headline,
    '',
    `| | DOM traversal | WebMCP direct | Saved |`,
    `| --- | ---: | ---: | ---: |`,
    `| Steps | ${domTraversal.steps} | ${webMcpDirect.steps} | ${domTraversal.steps - webMcpDirect.steps} |`,
    `| Tokens | ${formatCompact(domTraversal.totalTokens)} | ${formatCompact(webMcpDirect.totalTokens)} | ${formatCompact(frictionTax.tokensWasted)} |`,
    `| Cost | ${formatUsd(domTraversal.costUsd)} | ${formatUsd(webMcpDirect.costUsd)} | ${formatUsd(frictionTax.costWastedUsd)} |`,
    `| Latency | ${(domTraversal.latencyMs / 1000).toFixed(1)}s | ${(webMcpDirect.latencyMs / 1000).toFixed(1)}s | ${frictionTax.secondsWasted.toFixed(1)}s |`,
    `| Failure risk | ${(domTraversal.failureProbability * 100).toFixed(1)}% | ${(webMcpDirect.failureProbability * 100).toFixed(1)}% | ${(frictionTax.failureProbabilityDelta * 100).toFixed(1)}pp |`,
    '',
    `<sub>Per user transaction, modelled for a **${scorecard.benchmark.goal}** flow at ${scorecard.benchmark.pricing.model} rates. Estimates — see the report for stated assumptions.</sub>`,
    '',
  ];
}

function renderPillarSection(scorecard: AgentScorecard): string[] {
  const rows = scorecard.pillars.map((pillar) => {
    const ratio = pillar.maxPoints > 0 ? pillar.weightedPoints / pillar.maxPoints : 0;
    return `| ${pillar.label} | ${meter(ratio)} | ${pillar.weightedPoints.toFixed(1)} / ${pillar.maxPoints} |`;
  });

  return ['### Pillars', '', '| Pillar | | Score |', '| --- | --- | ---: |', ...rows, ''];
}

function renderIssueSection(issues: AuditIssue[], maxIssues: number): string[] {
  if (issues.length === 0) return ['### Issues', '', 'No issues found. 🎉', ''];

  const shown = issues.slice(0, maxIssues);
  const rows = shown.map(
    (issue) =>
      `| ${SEVERITY_ICON[issue.severity]} | **${escapePipes(issue.title)}** | ${
        issue.deductionPoints > 0 ? `−${issue.deductionPoints.toFixed(2)}` : '—'
      } | ${escapePipes(issue.remediation)} |`,
  );

  const lines = [
    `### Top deductions`,
    '',
    '| | Issue | Points | Fix |',
    '| :-: | --- | ---: | --- |',
    ...rows,
    '',
  ];

  if (issues.length > shown.length) {
    lines.push(`<sub>${issues.length - shown.length} further issue(s) omitted.</sub>`, '');
  }

  return lines;
}

/**
 * Generated code for the costliest issue.
 *
 * One issue, not all of them: a comment that dumps every snippet is a comment
 * nobody reads. The single highest-value fix is the one worth putting in front
 * of a reviewer.
 */
function renderRemediationSection(result: AuditRunResult): string[] {
  const [top] = result.scorecard.issues.filter((issue) => issue.deductionPoints > 0);
  if (!top) return [];

  let bundle;
  try {
    bundle = generateRemediation(top, result.report.data);
  } catch {
    // Code generation must never be the reason a CI comment fails to post.
    return [];
  }

  const tab = bundle.tabs.find((entry) => entry.id === 'browser-native') ?? bundle.tabs[0];
  if (!tab) return [];

  return [
    '<details>',
    `<summary><b>Suggested fix for the biggest deduction</b> — ${escapeHtml(top.title)} (−${top.deductionPoints.toFixed(2)})</summary>`,
    '',
    bundle.summary,
    '',
    '```javascript',
    tab.code.trimEnd(),
    '```',
    '',
    '</details>',
  ];
}

/** A five-cell bar that renders the same width in any markdown viewer. */
function meter(ratio: number): string {
  const filled = Math.round(Math.min(1, Math.max(0, ratio)) * 5);
  return '█'.repeat(filled) + '░'.repeat(5 - filled);
}

/** A pipe inside a cell would split the column. */
function escapePipes(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function escapeHtml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function formatUsd(value: number): string {
  if (!Number.isFinite(value)) return '$0.00';
  return value >= 0.01 ? `$${value.toFixed(2)}` : `$${value.toFixed(4)}`;
}

function formatCompact(value: number): string {
  if (!Number.isFinite(value)) return '0';
  if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(1)}M`;
  if (value >= 1_000) return `${(value / 1_000).toFixed(1)}k`;
  return String(Math.round(value));
}
