/**
 * Bundles the CLI.
 *
 * The core engine lives at the repository root rather than in `packages/`, so
 * it is bundled in at build time under the `@agentgrade/core` alias rather than
 * declared as a dependency. That keeps the published package free of a
 * circular workspace link, and leaves it with exactly one runtime dependency —
 * Playwright, which ships platform binaries and must stay external.
 */

import { execFileSync } from 'node:child_process';
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..');
const outDir = resolve(here, 'dist');

const manifest = JSON.parse(await readFile(resolve(here, 'package.json'), 'utf8'));

/** Resolves `@agentgrade/core` to the root engine's source. */
const coreAlias = {
  name: 'agentgrade-core-alias',
  setup(pluginBuild) {
    pluginBuild.onResolve({ filter: /^@agentgrade\/core$/ }, () => ({
      path: resolve(repoRoot, 'src', 'index.ts'),
    }));
    pluginBuild.onResolve({ filter: /^@agentgrade\/core\// }, (args) => ({
      path: resolve(repoRoot, 'src', `${args.path.replace('@agentgrade/core/', '')}.ts`),
    }));
  },
};

const shared = {
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',
  sourcemap: true,
  // Playwright ships browser binaries and native bindings; bundling it would
  // break its runtime path resolution.
  external: ['playwright', 'playwright-core'],
  plugins: [coreAlias],
  define: {
    __AGENTGRADE_VERSION__: JSON.stringify(manifest.version),
  },
  logLevel: 'warning',
};

await mkdir(outDir, { recursive: true });

// The binary is built from `src/bin.ts`, the only module that runs on import.
// No `banner` here: `src/bin.ts` already starts with a shebang and esbuild
// preserves it, so adding one would emit it twice and break the parse.
await build({
  ...shared,
  entryPoints: [resolve(here, 'src', 'bin.ts')],
  outfile: resolve(outDir, 'cli.js'),
});

await build({
  ...shared,
  entryPoints: [resolve(here, 'src', 'index.ts')],
  outfile: resolve(outDir, 'index.js'),
});

// The bin entry has to be executable when npm links or installs it.
await chmod(resolve(outDir, 'cli.js'), 0o755);

// esbuild does not emit declarations. The CLI bundles the engine's *code*, so
// it has to ship the engine's *types* too — a declaration file referencing
// `../src` or `@agentgrade/core` would resolve to nothing in the published
// tarball, and every consumer would get TS2307 (or a silent `any` under
// `skipLibCheck`).
//
// So: emit the engine's declarations into `dist/core/`, and hand-write a
// self-contained `index.d.ts` whose only import is that shipped tree.
execFileSync(
  process.execPath,
  [
    resolve(repoRoot, 'node_modules', 'typescript', 'bin', 'tsc'),
    '-p',
    resolve(repoRoot, 'tsconfig.build.json'),
    '--emitDeclarationOnly',
    '--declarationMap',
    'false',
    '--outDir',
    resolve(outDir, 'core'),
  ],
  { cwd: repoRoot, stdio: 'inherit' },
);

await writeFile(
  resolve(outDir, 'index.d.ts'),
  `// Generated by packages/cli/build.mjs — do not edit.
//
// The engine's own declarations are shipped alongside, in ./core/, because the
// CLI bundles the engine rather than depending on it.
import type {
  AgentScorecard,
  AuditReport,
  AuditIssue,
  ScannerOptions,
} from './core/index.js';

export type { AgentScorecard, AuditReport, AuditIssue } from './core/index.js';

/** Options for {@link runAudit}. */
export interface RunAuditOptions {
  /** Minimum score the target must reach to pass. */
  threshold: number;
  /** Navigation timeout in milliseconds. */
  timeoutMs?: number;
  /** Egress proxy for both navigation and descriptor fetches. */
  proxy?: string;
  /** Goal for the synthetic evaluator. Omit to skip the active evaluation. */
  syntheticGoal?: string;
  /** Extra HTTP headers, e.g. an auth header for a protected staging site. */
  headers?: Record<string, string>;
  /** Progress sink, called with a one-line status. */
  onProgress?: (message: string) => void;
  /** Reuse a browser across several audits. */
  browser?: ScannerOptions['browser'];
}

/** The outcome of one CLI audit. */
export interface AuditRunResult {
  url: string;
  report: AuditReport;
  scorecard: AgentScorecard;
  threshold: number;
  /** True when \`scorecard.overallScore >= threshold\`. */
  passed: boolean;
  durationMs: number;
}

/** Output formats \`--format\` accepts. */
export type OutputFormat = 'pretty' | 'json' | 'markdown';

/** Everything the CLI writes to, injected so tests can capture it. */
export interface CliIo {
  stdout: (chunk: string) => void;
  stderr: (chunk: string) => void;
  writeFile?: (path: string, contents: string) => Promise<void>;
}

/** Parsed command line. */
export interface ParsedArgs {
  command: 'audit' | 'help' | 'version';
  url: string | null;
  threshold: number;
  format: OutputFormat;
  output: string | null;
  proxy: string | null;
  timeoutMs: number | null;
  syntheticGoal: string | null;
  headers: Record<string, string>;
  quiet: boolean;
  maxIssues: number | null;
  color: boolean | null;
  error: string | null;
}

export interface MarkdownOptions {
  maxIssues?: number;
  includeRemediation?: boolean;
  title?: string;
}

export interface PrettyOptions {
  maxIssues?: number;
  color?: boolean;
  width?: number;
}

/** The JSON document \`--format json\` writes. */
export interface JsonReportEnvelope {
  version: '1.0.0';
  url: string;
  passed: boolean;
  score: number;
  threshold: number;
  grade: string;
  scanStatus: string;
  durationMs: number;
  generatedAt: string;
  frictionTax: {
    costUsd: number;
    secondsWasted: number;
    tokensWasted: number;
    headline: string;
  };
  pillars: Array<{ pillar: string; score: number; earned: number; max: number }>;
  issues: Array<{
    id: string;
    title: string;
    severity: string;
    pillar: string;
    deductionPoints: number;
    remediation: string;
  }>;
  scorecard: AgentScorecard;
  report: AuditReport;
}

/**
 * Exit codes. 1 and 3 are distinct on purpose: a red build has to say whether
 * the site regressed or the deployment was unreachable.
 */
export declare const EXIT_CODES: {
  readonly pass: 0;
  readonly belowThreshold: 1;
  readonly usage: 2;
  readonly scanFailed: 3;
};
export declare const FORMATS: readonly ['pretty', 'json', 'markdown'];
export declare const DEFAULT_THRESHOLD: number;
/** Identifies an AgentGrade comment so a workflow can update it in place. */
export declare const COMMENT_MARKER: string;

export declare function runAudit(url: string, options: RunAuditOptions): Promise<AuditRunResult>;
export declare function normaliseUrl(input: string): string;
export declare function formatJson(result: AuditRunResult): string;
export declare function formatMarkdown(result: AuditRunResult, options?: MarkdownOptions): string;
export declare function formatPretty(result: AuditRunResult, options?: PrettyOptions): string;
export declare function parseArgs(argv: string[]): ParsedArgs;
export declare function main(argv: string[], io?: CliIo): Promise<number>;

export interface TableColumn {
  header: string;
  align?: 'left' | 'right';
  maxWidth?: number;
}
export interface Style {
  (value: string, ...styles: string[]): string;
  readonly enabled: boolean;
}
export declare function createStyle(enabled?: boolean): Style;
export declare function stripAnsi(value: string): string;
export declare function supportsColor(stream?: { isTTY?: boolean }): boolean;
export declare function renderBar(value: number, max: number, width?: number): string;
export declare function renderTable(options: {
  columns: TableColumn[];
  rows: string[][];
  gutter?: string;
  indent?: string;
  style?: Style;
}): string;
`,
  'utf8',
);

process.stdout.write(`agentgrade CLI built to ${outDir}\n`);
